Repository codestates-seb/seb40_pre_010, pull requests merged in 2022-11, with the labels that each got.

#66 ⛲ feat : delete 구현
  front/src/components/Login.js
  front/src/pages/AskQuestion.js
  front/src/pages/QuestionList.js
  front/src/pages/QuestionPost.js
  front/src/setupProxy.js
Labels: 🚨 BugFix, ⛲ Feature, 🖼 HTML&CSS

#68 🚨 fix : 자료형 변경, useEffect 최소화
  front/src/components/User-card.js
  front/src/pages/QuestionList.js
  front/src/pages/QuestionPost.js
Labels: 🚨 BugFix, 🔨 Refactor

#69 ⛲ feat : 반응형 토글 버튼 추가
  front/src/_actions/index.js
  front/src/_actions/toggleState.js
  front/src/components/Nav-Side1.js
  front/src/components/TopMainNav.js
Labels: ⛲ Feature

#70 ⛲ feat : 반응형 토글버튼 구현 완성
  front/src/_actions/index.js
  front/src/_actions/inputState.js
  front/src/components/Nav-Side1.js
  front/src/components/SignUp.js
  front/src/components/TopMainNav.js
Labels: ⛲ Feature

#71 ⛲ feat : 삼각형 추가
  front/src/components/Post.js
  front/src/components/Triangle.js
  front/src/pages/QuestionPost.js
Labels: 🔨 Refactor, 🖼 HTML&CSS

#73 ⛲ feat : 회원가입 유효성 검사 구현 완료
  front/src/components/SignUp.js
Labels: ⛲ Feature

#72 🚨 태그 영역확장, ⛲ 유효성 완
  front/src/components/Input-tag.js
  front/src/pages/QuestionPost.js
Labels: 🚨 BugFix, ⛲ Feature

#74 🚨 fix : QuestionPost 병합 완료
  front/src/pages/AskQuestion.js
  front/src/pages/QuestionList.js
  front/src/pages/QuestionPost.js
  front/src/setupProxy.js
Labels: 🚨 BugFix, 🖼 HTML&CSS

#75 🔨 refactor: 주석 삭제!
  front/src/App.js
  front/src/components/Nav-Side2.js
  front/src/components/Post.js
  front/src/components/User-card.js
  front/src/pages/QuestionList.js
  front/src/pages/QuestionPost.js
Labels: 🔨 Refactor, 🖼 HTML&CSS

#76 📄 docs : 주석 삭제 및 사용하지 않는 파일 정리
  front/src/_actions/index.js
  front/src/_actions/inputState.js
  front/src/_actions/user.js
  front/src/components/Login.js
  front/src/components/LogoutModal.js
  front/src/components/Nav-Side1.js
  front/src/components/SearchInput.js
  front/src/components/SignUp.js
  front/src/components/TopMainNav.js
  front/src/utils/cookie.js
Labels: 📄 Docs

#77 🔨 refactor : 리팩토링
  front/src/pages/AskQuestion.js
Labels: 🔨 Refactor

#78 🔨 refactor : 리팩토링
  README.md
  front/package-lock.json
  front/package.json
  front/src/App.css
  front/src/App.js
  front/src/_actions/index.js
  front/src/_actions/toggleState.js
  front/src/components/Accordion.js
  front/src/components/Alert.js
  front/src/components/Footer.js
  front/src/components/Input-tag.js
  front/src/components/Login.js
  front/src/components/LogoutModal.js
  front/src/components/Nav-Side1.js
  front/src/components/Nav-Side2.js
  front/src/components/Pagination.js
  front/src/components/Post.js
  front/src/components/SearchInput.js
  front/src/components/SignUp.js
  front/src/components/Tag.js
  front/src/components/TextEditor.js
  front/src/components/TopMainNav.js
  front/src/components/Triangle.js
  front/src/components/User-card.js
  front/src/components/post.js
  front/src/index.js
  front/src/pages/AskQuestion.js
  front/src/pages/Home.js
  front/src/pages/QuestionList.js
  front/src/pages/QuestionPost.js
  front/src/pages/Tags.js
  front/src/setupProxy.js
  front/src/static/dummy2.json
  front/src/static/dummy3.json
Labels: 🔨 Refactor
